---
- name: win_update module demo for team
  hosts: all
  become: false
  gather_facts: false
  tasks:
  - name: Install all security, and critical updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - Drivers
      state: installed
      reboot: yes