---
- name: win_chocolatey module demo to install prebuilt packages 
# website to look at other support packages https://community.chocolatey.org/packages
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install firefox
      win_chocolatey:
      name: firefox
      state: present

    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest