---
- name: win_update module to update security, crital, and drivers
  hosts: all
  become: false
  gather_facts: true
  tasks:
  - name: Install all security, critical, driver updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - Upgrades
        - Drivers
        - Updates
      state: installed
      reject_list:
        - Hewlett-Packard - USB - 3/4/2019 12:00:00 AM - 48.2.4483.1963 
      reboot: yes