---
- name: win_user module to manage local users
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Ensure user bob is present
      win_user:
        name: {{ user }}
        password: {{ password }}
        state: present
        groups:
          - {{ groups }}