---
- name: win_update module 
  hosts: all
  become: false
  gather_facts: true
  tasks:
  - name: Install all updates and reboot
    win_updates:
      category_names: "*"
      state: installed
      reboot: yes
      reboot_time: 3600 
      #Sometimes laptops fail to reconnect. 